### PR TITLE
fix: stop querying DOM every frame in drawWeatherUI

### LINKED ISSUE #69: `drawWeatherUI()` queries DOM every frame without throttling
## Description

`drawWeatherUI()` is called every frame from the game loop (`main.js` line 1011):

```js
export function drawWeatherUI(ctx) {
    updateWeatherUIPanelPosition();
    updateWeatherUIPanelContent();
}
```

Each call queries the DOM (`querySelector` for 7+ elements), reads text content, and sets `textContent` on all of them. At 60fps, this means 420+ DOM queries per second.

The weather UI only needs updating when time changes or weather changes, which the event listeners already handle in `init()`.

## File
- `public/scripts/weather.js` (lines 627-631)

## Suggested Fix
Remove the per-frame DOM updates and rely on the existing event-driven updates, or add a dirty flag that only triggers DOM updates when state actually changes.

### PR DESCRIPTION
**Pull request by Gabriel-Andraade**
fix #69 

drawWeatherUI() was calling updateWeatherUIPanelPosition() and updateWeatherUIPanelContent() on every game loop tick, causing unecessary DOM queries

## Summary by CodeRabbit

* **Refactor**
  * Weather UI rendering no longer runs every frame; per-frame UI hook removed.
  * UI updates now occur via system event listeners (time, day, language, resize) and when weather is randomized, improving responsiveness and reliability.

### CODE REVIEW

File: public/scripts/weather.js [hunk 1]
```diff
@@ -619,13 +619,12 @@ export function drawWeatherEffects(ctx, player, canvas) {
...
+ * Weather UI is now updated exclusively via event listeners
+ * (timeChanged, dayChanged, languageChanged, resize, and direct calls in randomizeWeather).
+ * `@param` {CanvasRenderingContext2D} _ctx - Unused; retained for backward compatibility with main.js caller.
  * @returns {void}
  */
-export function drawWeatherUI(ctx) {
-  // O painel agora é overlay HTML ancorado no canto do canvas
-  updateWeatherUIPanelPosition();
-  updateWeatherUIPanelContent();
+export function drawWeatherUI(_ctx) {
```
Comment (cirospaciari) [inline public/scripts/weather.js]: if is empty is better to just remove this code and all calls from it
